import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import setList from "../data/set-list.json";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>MTG ALPHA</h1>

        <div
          style={{
            textAlign: "center",
            margin: "0 auto",
            width: "700px",
            display: "flex",
            flexWrap: "wrap",
          }}
        >
          <HomeSection name="Card Images" href="/cards" />
          <HomeSection name="Card List" href="/cards" />
          <HomeSection name="About Alpha" href="/cards" />
          <HomeSection name="Alpha Print Runs" href="/cards" />
          <HomeSection name="Open Booster Pack" href="/random-pack" />
          <HomeSection name="Open Starter Deck" href="/cards" />
        </div>
      </main>
    </>
  );
}

const HomeSection = ({ name, href }) => {
  return (
    <Link href={href}>
      <div
        style={{ width: "350px", height: "200px", border: "1px solid black" }}
      >
        {name}
      </div>
    </Link>
  );
};
